name: MLiP
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.5.0
  - jupyter=1.0.0
  - numpy=1.21.5
  - openpyxl=3.0.9
  - pandas=1.3.5
  - pip=21.2.2
  - plotly==5.5.0
  - python=3.8.12
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - seaborn=0.11.2